@startuml LibraryContext
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(libraryuser, "User", "Main User of the system")

System(loadmange, "Load a book")

Rel(libraryuser, loadmange, "Access")
@enduml